[source]
type = "Bitcoin"
rpc_url = "https://bitcoin-rpc.publicnode.com"
rpc_interval = 30

[intersect]
type = "Tip"

[sink]
# type = "Stdout"
type = "FileRotate"
output_path = "/tmp/oura-btc/mainnet"
output_format = "JSONL"
max_bytes_per_file = 1_000_000
max_total_files = 10
compress_files = false
